title: Jianru Duan's Homepage
page-top-title: Jianru Duan 段剑儒
top-section-bg-text: Jianru Duan's Homepage
home-subtitle: Jianru Duan&ensp;|&ensp;段剑儒
copyright-text: '&copy; 2025 Jianru Duan. Hosted by GitHub Pages with SenLi Theme.'
